export {default as ThanksForOrder} from "./ThanksForOrder"
export {default as ScheduleModal} from "./ScheduleModal"
export {default as EditProfileModal} from "./EditProfileModal"
export {default as AddressBookModal} from "./AddressBookModal"
export {default as AddCardModal} from "./AddCardModal"